### ISSUE TITLE
Interesting runtime discoveries

### ISSUE THREAD

**Issue by RuvinshteynM** [MRuvinshteyn/eegMr#1]
When running the MergeSort algorithm on the different list lengths, I kept getting the longest runtime for a list of length 1. Is this meant to happen or is this a problem that needs to be looked at?

**Comment by RuvinshteynM** [comment]
I fixed it; it turns out that the runtime was longer on the first array that was put under the MergeSort operation. I am yet to understand why this is so.

**Comment by ghost** [comment]
This is because of the initialization of a bunch of things. [Here](http://stackoverflow.com/questions/31858301/why-is-there-such-a-big-difference-on-time-between-first-nanotime-call-and-the) is a link for reference.

**Comment by Ero2000** [comment]
So, are we going to work on the readme file?
